// Code generated by MockGen. DO NOT EDIT.
// Source: path/to/your/project/club_hub_port.go

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	reflect "reflect"

	"github.com/golang/mock/gomock"
	
	"github.com/unawaretub86/club-hub/src/core/domain"
)

// MockRepositoryPort is a mock of ClubHubPort interface.
type MockRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryPortMockRecorder
}

// MockRepositoryPortMockRecorder is the mock recorder for MockRepositoryPort.
type MockRepositoryPortMockRecorder struct {
	mock *MockRepositoryPort
}

// NewMockRepositoryPort creates a new mock instance.
func NewMockRepositoryPort(ctrl *gomock.Controller) *MockRepositoryPort {
	mock := &MockRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryPort) EXPECT() *MockRepositoryPortMockRecorder {
	return m.recorder
}

// SaveCompany mocks base method.
func (m *MockRepositoryPort) SaveCompany(company domain.Company) (*domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCompany", company)
	ret0, _ := ret[0].(*domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompany mocks base method.
func (m *MockRepositoryPort) GetCompany(params map[string]string) (domain.Companies, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompany", params)
	ret0, _ := ret[0].(domain.Companies)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCompany mocks base method.
func (m *MockRepositoryPort) UpdateCompany(id uint, company domain.Company) (*domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompany", id, company)
	ret0, _ := ret[0].(*domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyByFranchise mocks base method.
func (m *MockRepositoryPort) GetCompanyByFranchise(params map[string]string) (*domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyByFranchise", params)
	ret0, _ := ret[0].(*domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyByInformation mocks base method.
func (m *MockRepositoryPort) GetCompanyByInformation(params map[string]string) (*domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyByInformation", params)
	ret0, _ := ret[0].(*domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyByOwner mocks base method.
func (m *MockRepositoryPort) GetCompanyByOwner(params map[string]string) (*domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyByOwner", params)
	ret0, _ := ret[0].(*domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveCompany indicates an expected call of SaveCompany.
func (mr *MockRepositoryPortMockRecorder) SaveCompany(company interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCompany", reflect.TypeOf((*MockRepositoryPort)(nil).SaveCompany), company)
}

// GetCompany indicates an expected call of GetCompany.
func (mr *MockRepositoryPortMockRecorder) GetCompany(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompany", reflect.TypeOf((*MockRepositoryPort)(nil).GetCompany), params)
}

// UpdateCompany indicates an expected call of UpdateCompany.
func (mr *MockRepositoryPortMockRecorder) UpdateCompany(id interface{}, company interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompany", reflect.TypeOf((*MockRepositoryPort)(nil).UpdateCompany), id, company)
}

// GetCompanyByFranchise indicates an expected call of GetCompanyByFranchise.
func (mr *MockRepositoryPortMockRecorder) GetCompanyByFranchise(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyByFranchise", reflect.TypeOf((*MockRepositoryPort)(nil).GetCompanyByFranchise), params)
}

// GetCompanyByInformation indicates an expected call of GetCompanyByInformation.
func (mr *MockRepositoryPortMockRecorder) GetCompanyByInformation(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyByInformation", reflect.TypeOf((*MockRepositoryPort)(nil).GetCompanyByInformation), params)
}

// GetCompanyByOwner indicates an expected call of GetCompanyByOwner.
func (mr *MockRepositoryPortMockRecorder) GetCompanyByOwner(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyByOwner", reflect.TypeOf((*MockRepositoryPort)(nil).GetCompanyByOwner), params)
}
